name: sales_agent
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1
environment:
  sdk: ^3.8.0



dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  http: ^1.5.0
  path_provider: ^2.1.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  logger: ^2.6.1
  google_fonts: ^6.3.1
  flutter_screenutil: ^5.9.3
  hexcolor: ^3.0.1
  easy_localization: ^3.0.8
  network_info_plus: ^6.1.4
  equatable: ^2.0.7
  pinput: ^5.0.2
  sidebarx: ^0.17.2
  number_pad_keyboard: ^0.0.6
  flutter_styled_toast: ^2.2.1
  animated_text_kit: ^4.2.3
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.1
  table_calendar: ^3.2.0
  syncfusion_flutter_datagrid: ^30.1.38
  syncfusion_flutter_core: ^30.1.38
  glassmorphism: ^3.0.0
  animated_tree_view: ^2.3.0
  provider: ^6.1.5+1
  advanced_search: ^2.2.6+1
  uuid: ^4.2.1
  toastification: ^3.0.3
  carousel_slider: ^5.1.1
  observe_internet_connectivity: ^1.0.2
  package_info_plus: ^9.0.0
  icons_launcher: ^3.0.3
  intl_phone_number_input: ^0.7.5
  flutter_keyboard_visibility: ^6.0.0
  disk_space_plus: ^0.2.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  icons_launcher: ^3.0.3
  build_runner: any

  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/translations/
      - assets/icons/pass_enable.png
      - assets/icons/pass_hide.png
      - assets/icons/chec_unbox.svg
      - assets/icons/chek_box.svg
      - assets/icons/exit.svg
      - assets/icons/drawers/assortiment.svg
      - assets/icons/drawers/contragents.svg
      - assets/icons/drawers/history.svg
      - assets/icons/drawers/home.svg
      - assets/icons/drawers/orders.svg
      - assets/icons/drawers/settings.svg
      - assets/icons/home/human.svg
      - assets/icons/home/total.svg
      - assets/icons/home/await.svg
      - assets/icons/home/job.svg
      - assets/icons/home/save.svg
      - assets/icons/pop/trash.svg
      - assets/icons/pop/dialog_sablon.svg
      - assets/icons/pop/edit.svg
      - assets/icons/orders/search.svg
      - assets/icons/empti.svg
      - assets/icons/assortiment/box_asl.svg
      - assets/icons/assortiment/folder_open.svg
      - assets/icons/shopping_cart.svg
      - assets/icons/dawn.svg
      - assets/icons/trash.svg
      - assets/icons/add.svg
      - assets/icons/min.svg
      - assets/icons/trash_open.svg
      - assets/icons/toast/error_send.svg
      - assets/icons/toast/suces_send.svg
      - assets/icons/toast/no_signal.svg
      - assets/icons/toast/bubu_error.svg
      - assets/icons/toast/succes_pop.svg
      - assets/icons/toast/await_pop.svg
      - assets/icons/toast/save_order.svg
      - assets/icons/info_asl/arrow_left.svg
      - assets/icons/info_asl/arrow_right.svg
      - assets/icons/info_asl/non_image.svg
      - assets/icons/close.svg
      - assets/icons/non_photo.svg
      - assets/icons/photo.svg
      - assets/icons/splash_logo.svg
      - assets/icons/logo.png


